"""Acceptance tests for the realizable-misuse detector + repair
(bfo-agent-realizable-misuse-fix-SPEC Section 9).

Fixtures live under tests/fixtures/ and are regenerated by
scripts/make_rm_fixtures.py. Each reasons under the app's real BFO
(config.BFO_PATH) so a pass here matches the gate's full-signature verdict.
"""
import shutil
from pathlib import Path

import pytest
from rdflib import Graph, RDFS, OWL, URIRef

from app import realizable_misuse as rm
from app import config

FIX = Path(__file__).parent / "fixtures"
BFO = Path(config.BFO_PATH)

# fixture -> (class, expected pattern) it must detect
CASES = {
    "rm_p2": ("Creatine", "P2"),
    "rm_contra": ("CyclicDisposition", "CONTRA"),
    "rm_p1": ("MetabolicDisposition", "P1"),
}


def _repair(fixture, tmp_path):
    src = FIX / f"{fixture}.owl"
    work = tmp_path / f"{fixture}.owl"
    shutil.copy(src, work)
    res = rm.repair_file(work, BFO, out_path=work)
    return res, work


# --- Criterion 1: detector labels every fixture with the correct pattern -------
@pytest.mark.parametrize("fixture,cls,pattern", [(f, c, p) for f, (c, p) in CASES.items()])
def test_detect_pattern(fixture, cls, pattern):
    findings = {f["class"]: f["pattern"] for f in rm.detect_file(FIX / f"{fixture}.owl", BFO)}
    assert findings.get(cls) == pattern, findings
    # zero OTHER among the primary (root) defects
    assert "OTHER" not in [p for c, p in findings.items() if c == cls]


# --- Criterion 2: after repair, full-signature run is 0 unsat + consistent -----
@pytest.mark.parametrize("fixture", list(CASES) + ["rm_cascade"])
def test_repair_reaches_zero(fixture, tmp_path):
    res, work = _repair(fixture, tmp_path)
    assert res.after_unsat == 0, res.remaining
    g = Graph()
    g.parse(str(work))
    ok, unsat = rm._run(g, BFO)
    assert ok and not unsat


# --- Criterion 3: repair deletes 0 source-content axioms -----------------------
def test_p2_swaps_property_keeps_restriction(tmp_path):
    res, work = _repair("rm_p2", tmp_path)
    assert [t["rule"] for t in res.transforms] == ["R2"]
    g = Graph()
    g.parse(str(work))
    creatine = URIRef("http://davidkoepsell.com/bfo-agent/working#Creatine")
    props = set()
    for o in g.objects(creatine, RDFS.subClassOf):
        r = rm._restriction(g, o)
        if r:
            props.add(r[0])
    # the restriction survives, retyped to has-role; the corrupted prop is gone
    assert "RO_0000087" in props
    assert "BFO_0000196" not in props


def test_contra_drops_only_complement_keeps_source(tmp_path):
    res, work = _repair("rm_contra", tmp_path)
    assert [t["rule"] for t in res.transforms] == ["R4"]
    g = Graph()
    g.parse(str(work))
    disp = URIRef("http://davidkoepsell.com/bfo-agent/working#CyclicDisposition")
    has_complement = any(rm._is_complement(g, o) for o in g.objects(disp, RDFS.subClassOf))
    has_positive = any(rm._restriction(g, o) == ("BFO_0000054", "http://davidkoepsell.com/bfo-agent/working#MenstrualProcess")
                       for o in g.objects(disp, RDFS.subClassOf))
    assert not has_complement          # contradiction dropped
    assert has_positive                # source `realized in` kept


# --- Criterion 4: repairing roots heals dependents (cascade) -------------------
def test_cascade_root_heals_dependent(tmp_path):
    res, work = _repair("rm_cascade", tmp_path)
    assert res.before_unsat == 2 and res.after_unsat == 0
    touched = {t["class"] for t in res.transforms}
    # only the root was transformed; the dependent healed untouched
    assert "EnzymeCofactor" in touched
    assert "CofactorComplex" not in touched


# --- Criterion 5: re-gate passes; a re-broken fixture fails and would block -----
def test_repaired_passes_and_rebroken_fails(tmp_path):
    _, work = _repair("rm_p2", tmp_path)
    assert rm.detect_file(work, BFO) == []          # clean after repair
    # re-break: swap has-role back to the corrupted has-disposition property
    g = Graph()
    g.parse(str(work))
    for o in list(g.objects(None, OWL.onProperty)):
        if rm._frag(o) == "RO_0000087":
            s = next(g.subjects(OWL.onProperty, o))
            g.remove((s, OWL.onProperty, o))
            g.add((s, OWL.onProperty, URIRef(rm.OBO + "BFO_0000196")))
    broken = tmp_path / "broken.owl"
    g.serialize(destination=str(broken), format="xml")
    assert any(f["pattern"] == "P2" for f in rm.detect_file(broken, BFO))
